### ISSUE TITLE
Add option to pply chmod only to file with shebang

### ISSUE THREAD

**Issue by xgvargas** [shuangwhywhy/webpack-shebang-plugin#10]
Current version applies executable flag to all generated files, but in my case, only a few are executable and include a shebang, while others are just a bunch of libraries. However all of them got the execution flag, even those without a shebang .

It would be nice to have such control over the final result of the plugin.

Other than that it works fine, thanks!

**Comment by shuangwhywhy** [comment]
> Current version applies executable flag to all generated files, but in my case, only a few are executable and include a shebang, while others are just a bunch of libraries. However all of them got the execution flag, even those without a shebang .
> 
> It would be nice to have such control over the final result of the plugin.
> 
> Other than that it works fine, thanks!

Thanks for your suggestion! Fixed in the latest version. You can upgrade to 1.1.7 version now.
